export const constants = {
    GET_DATA_FOR_VOTE: 'GET_DATA_FOR_VOTE',
    INPUT_DONE: 'INPUT_DONE',
    TRIGGER_CHANGED: 'TRIGGER_CHANGED',
    SEARCH_TRIGGER_CHANGED: 'SEARCH_TRIGGER_CHANGED',
    OTHER_USER_INFO: 'OTHER_USER_INFO',
};