export const constants = {
    SET_MY_TODAY_AVG: 'SET_MY_TODAY_AVG',
    SET_MY_CURRENT_MONTH_AVG: 'SET_MY_CURRENT_MONTH_AVG',
    SET_MY_LAST_MONTH_AVG: 'SET_MY_LAST_MONTH_AVG',
    SET_LAST_MONTH_AVG_RATING: 'SET_LAST_MONTH_AVG_RATING',
    SET_YESTERDAY_AVG_RATING: 'SET_YESTERDAY_AVG_RATING',
};