import LocalizedStrings from 'react-native-localization';

export const constStrings = new LocalizedStrings({
    en: {
        updateInfo: 'Update',
        Comment: 'Comment:',
        Ratings: 'Ratings:',
        noUser: 'There is no such User',
        successfulRegister: 'Registration was successful!',
        emailNotCorporate: 'This email is not corporate. Please enter corporate email for registration.',
        alreadyRegistered: 'It seems you are already registered, please choose a different email',
        chooseDate: 'Choose Date',
        language: 'Language',
        server: 'Server',
        saveSettings: 'Save',
        cancel: 'Cancel',
        allUsers: 'All Users',
        chooseName: 'Choose name',
        fullName: 'Full Name',
        corporateEmail: 'Corporate Email',
        email: 'Email',
        dateOfBirth: 'Date of Birth',
        registration: 'Registration',
        signIn: 'Sign In',
        logIn: 'Log In',
        signUp: 'Sign Up',
        password: 'Password',
        currentPassword: '*Current Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm New Password',
        firstTimeHere: 'First time here? You need to',
        gender: 'Gender',
        infoAboutWork: 'Information About Your Workplace',
        country: 'Country',
        city: 'City',
        branch: 'Branch',
        department: 'Department',
        position: 'Position',
        comment: 'Comment',
        someComment: 'Some comment here...',
        rating: 'Rating',
        male: 'Male',
        female: 'Female',
        signOut: 'Sign Out',
        listOfNotRated: 'List of unvoted users',
        addReview: 'Add Review',
        writeComment: '*Write your comment here...',
        submit: 'Submit',
        myAvgRate: 'My average rate',
        today: 'Today',
        currentMonth: 'Current Month',
        lastMonth: 'Last Month',
        votes: '\n(number of votes',
        top3Users: 'Top 3 Users for last month',
        last3Users: 'Last 3 Users for last month',
        yesterdayTop: 'Yesterday Top 1',
        monthNames: {
            january: 'January',
            february: 'February',
            march: 'March',
            april: 'April',
            may: 'May',
            june: 'June',
            july: 'July',
            august: 'August',
            september: 'September',
            october: 'October',
            november: 'November',
            december: 'December',
        },
    },

    ru: {
        updateInfo: 'Редактировать',
        Comment: 'Комментарий',
        Ratings: 'Рейтинг:',
        noUser: 'Пользователь не найден',
        successfulRegister: 'Регистрация прошла успешно!',
        emailNotCorporate: 'Введенная электронная почта не корпоративная. Пожалуйста введите корпоративную почту для регистрации.',
        alreadyRegistered: 'Похоже Вы уже зарегистрированы, пожалуйста, введите другую электронную почту',
        chooseDate: 'Выберите дату',
        language: 'Язык',
        server: 'Сервер',
        saveSettings: 'Сохранить',
        cancel: 'Отменить',
        allUsers: 'Все Пользователи',
        chooseName: 'Выберите Имя',
        fullName: 'Полное Имя',
        corporateEmail: 'Корпоративная Электронная Почта',
        email: 'Электронная Почта',
        dateOfBirth: 'Дата Рождения',
        registration: 'Регистрация',
        signIn: 'Авторизация',
        logIn: 'Войти',
        signUp: 'Регистрация',
        password: 'Пароль',
        currentPassword: '*Нынешний Пароль',
        newPassword: 'Новый Пароль',
        confirmPassword: 'Подтвердить Новый Пароль',
        firstTimeHere: 'Впервые здесь? Вам нужна',
        gender: 'Пол',
        infoAboutWork: 'Информация о Вашем Рабочем Месте',
        country: 'Страна',
        city: 'Город',
        branch: 'Компания',
        department: 'Отдел',
        position: 'Позиция',
        comment: 'Комментарий',
        someComment: 'Здесь написан комментарий...',
        rating: 'Оценка',
        male: 'Мужской',
        female: 'Женский',
        signOut: 'Выйти',
        listOfNotRated: 'Список непроголосованных пользователей',
        addReview: 'Добавить Оценку',
        writeComment: '*Напиши свой комментарий...',
        submit: 'Подтвердить',
        myAvgRate: 'Моя средняя оценка',
        today: 'Сегодня',
        currentMonth: 'Текущий Месяц',
        lastMonth: 'Прошлый Месяц',
        votes: '\n(количество оценок',
        top3Users: 'Toп 3 Пользователей за прошлый месяц',
        last3Users: 'Последние 3 Пользователя за прошлый месяц',
        yesterdayTop: 'Вчерашний Tоп 1',
        monthNames: {
            january: 'Январь',
            february: 'Февраль',
            march: 'Март',
            april: 'Апрель',
            may: 'Май',
            june: 'Июнь',
            july: 'Июль',
            august: 'Август',
            september: 'Сентябрь',
            october: 'Октябрь',
            november: 'Ноябрь',
            december: 'Декабрь',
        },
    },

    az: {
        updateInfo: 'Yenilə',
        Comment: 'Şərh',
        Ratings: 'Reytinq:',
        noUser: 'Bu adla istifadəçi tapılmadı',
        successfulRegister: 'Qeydiyyat uğurlu keçdi!',
        emailNotCorporate: 'Bu elektron ünvan korporativ deyil. Lütfən qeydiyyat üçün korporativ elektron ünvan qeyd edin.',
        alreadyRegistered: 'Qeyd etdiyiniz elektron ünvan sistemdə artıq qeyd olunub, lütfən başqa elektron ünvanı qeyd edin.',
        chooseDate: 'Tarixi seçin',
        language: 'Dil',
        server: 'Server',
        saveSettings: 'Yadda Saxla',
        cancel: 'Ləğv Et',
        allUsers: 'Bütün İstifadəçilər',
        chooseName: 'İstifadəçinin adını seç',
        fullName: 'Ad, Soyad, Ata adı',
        corporateEmail: 'Korporativ Elektron Ünvan',
        email: 'Elektron Ünvan',
        dateOfBirth: 'Doğum Tarixi',
        registration: 'Qeydiyyat',
        signIn: 'Avtorizasiya',
        logIn: 'Daxil Ol',
        signUp: 'Qeydiyyat',
        password: 'Şifrə',
        currentPassword: '*Cari Şifrə',
        newPassword: 'Yeni Şifrə',
        confirmPassword: 'Yeni Şifrəni Təsdiqlə',
        firstTimeHere: 'İlk dəfə burdasız? Sizə lazımdır',
        gender: 'Cins',
        infoAboutWork: 'İş yeri haqqında məlumat',
        country: 'Ölkə',
        city: 'Şəhər',
        branch: 'Kompaniya',
        department: 'Şöbə',
        position: 'Pozisiya',
        comment: 'Komment',
        someComment: 'Burada komment yazılıb...',
        rating: 'Qiymət',
        male: 'Kişi',
        female: 'Qadın',
        signOut: 'Profildən Çıx',
        listOfNotRated: 'Səs vermədiyiniz istifadəçilər',
        addReview: 'Rəy Əlavə Etmək',
        writeComment: '*Kommentini burada yaz...',
        submit: 'Qəbul Et',
        myAvgRate: 'Mənim ortalama qiymətləndirməm',
        today: 'Bugün',
        currentMonth: 'Bu Ay',
        lastMonth: 'Keçən Ay',
        votes: '\n(rəylərin sayı',
        top3Users: 'Otən ayın Top 3 İstifadəçisi',
        last3Users: 'Otən ayın Axır 3 İstifadəçisi',
        yesterdayTop: 'Dünənin Top 1 İstifadəçisi',
        monthNames: {
            january: 'Yanvar',
            february: 'Fevral',
            march: 'Mart',
            april: 'Aprel',
            may: 'May',
            june: 'İyun',
            july: 'İyul',
            august: 'Avqust',
            september: 'Sentyabr',
            october: 'Oktyabr',
            november: 'Noyabr',
            december: 'Dekabr',
        },
    },
});
