export const constants = {
    SET_POSITION: 'SET_POSITION',
    SET_UPDATE_INFO: 'SET_UPDATE_INFO',
    SET_SELECTED_DEPARTMENT: 'SET_SELECTED_DEPARTMENT',
    SET_SELECTED_POS: 'SET_SELECTED_POS',
    SET_DEPT: 'SET_DEPT',
    SET_DEPARTMENT_AND_POSITION: 'SET_DEPARTMENT_AND_POSITION',
};