export const constants = {

    SEARCH_INFO: 'SEARCH_INFO',
    START_SEARCH: 'START_SEARCH',
    SET_COMMENT_DATE: 'SET_COMMENT_DATE',
    DATE_SET: 'DATE_SET',
    SET_LOCALIZATION_FOR_TAB: 'SET_LOCALIZATION_FOR_TAB',
};