export const constants = {
    ALL_USERS_GET_USERS: 'ALL_USERS_GET_USERS',
    ALL_USERS_INPUT_DONE: 'ALL_USERS_INPUT_DONE',
    ALL_USERS_TRIGGER_CHANGED: 'ALL_USERS_TRIGGER_CHANGED',
    ALL_USERS_SEARCH_TRIGGER_CHANGED: 'ALL_USERS_SEARCH_TRIGGER_CHANGED',
    ALL_USER_INFO: 'ALL_USER_INFO',
    IS_ALL_USER: 'IS_ALL_USER',
};